package practica4;

public class Deportes extends javax.swing.JFrame {
 
    Jugador jugador[]=new Jugador[20];
    /**
     * Creates new form Deportes
     */
    public Deportes() {
        initComponents();
          for(int i=0;i<20;i++){
            jugador[i] = new Jugador();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtNombreJ = new javax.swing.JTextField();
        TxtPosicion = new javax.swing.JTextField();
        TxtSueldo = new javax.swing.JTextField();
        TxtValorM = new javax.swing.JTextField();
        BtnRegistar = new javax.swing.JButton();
        BtnConsultar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        LblNotificacion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 0, 153));
        jPanel1.setAutoscrolls(true);
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel2.setText("Nombre del jugador:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel3.setText("Victorias:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel4.setText("Puntos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel5.setText("Dorsal:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 50, -1));

        TxtNombreJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreJActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNombreJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 130, -1));

        TxtPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPosicionActionPerformed(evt);
            }
        });
        jPanel1.add(TxtPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 130, -1));
        jPanel1.add(TxtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 130, -1));
        jPanel1.add(TxtValorM, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 130, -1));

        BtnRegistar.setBackground(new java.awt.Color(255, 204, 255));
        BtnRegistar.setForeground(new java.awt.Color(255, 51, 204));
        BtnRegistar.setText("Registrar ");
        BtnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 90, -1));

        BtnConsultar.setBackground(new java.awt.Color(255, 204, 255));
        BtnConsultar.setForeground(new java.awt.Color(255, 51, 204));
        BtnConsultar.setText("Consultar");
        BtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        BtnLimpiar.setBackground(new java.awt.Color(255, 204, 255));
        BtnLimpiar.setForeground(new java.awt.Color(255, 51, 204));
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 90, -1));

        BtnEliminar.setBackground(new java.awt.Color(255, 204, 255));
        BtnEliminar.setForeground(new java.awt.Color(255, 51, 204));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 90, -1));

        LblNotificacion.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(LblNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 130, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("LIGA  FEMENIL TAPATIA 2023");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 210, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreJActionPerformed

    private void BtnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistarActionPerformed
        // TODO add your handling code here:
             
        for(int i=0;i<20;i++){
            if("obj".equals(jugador[i].getNombreJ())){
                jugador[i].setNombreJ(TxtNombreJ.getText());
                jugador[i].setPosicion(TxtPosicion.getText());
                jugador[i].setValorMer(Integer.parseInt(TxtValorM.getText()));
                jugador[i].setSueldo(Float.parseFloat(TxtSueldo.getText()));
                
                i=20;
                LblNotificacion.setText("Registro exitoso");
                
            }
        }
    }//GEN-LAST:event_BtnRegistarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
        TxtNombreJ.setText("");
        TxtPosicion.setText("");
        TxtSueldo.setText("");
        TxtValorM.setText("");
        TxtNombreJ.requestFocus();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here:
        if(TxtNombreJ.getText().equals("")==false){
            for(int i=0;i<20;i++){
                if(TxtNombreJ.getText().equals(jugador[i].getNombreJ())){
                   for(int j=i;j<20;j++){
                     if(jugador[j].getNombreJ().equals("obj")==false){
                   
                       jugador[j].setNombreJ(jugador[j+1].getNombreJ());
                       jugador[j].setPosicion(jugador[j+1].getPosicion());                            
                       jugador[j].setSueldo(jugador[j+1].getSueldo());                            
                       jugador[j].setValorMer(jugador[j+1].getValorMer());
                       LblNotificacion.setText("Dato eliminado");
                       i=20;
                        } 
                    }
                } 
                
            }
        }else if(TxtPosicion.getText().equals("")==false){
             for(int i=0;i<20;i++){
                if(TxtPosicion.getText().equals(jugador[i].getPosicion())){
                    for(int j=i;j<20;j++){
                        if(jugador[j].getPosicion().equals("obj")==false){
                           jugador[j].setNombreJ(jugador[j+1].getNombreJ());
                           jugador[j].setPosicion(jugador[j+1].getPosicion());                            
                           jugador[j].setSueldo(jugador[j+1].getSueldo());                            
                           jugador[j].setValorMer(jugador[j+1].getValorMer());
                           LblNotificacion.setText("Dato eliminado");
                            i=20;
                        }
                    }
                }
             }
               
        }else if(TxtSueldo.getText().equals("")==false){
            for(int i=0;i<20;i++){
                if(Float.parseFloat(TxtSueldo.getText())==jugador[i].getSueldo()){
                     for(int j=i;j<20;j++){
                        if(jugador[j].getSueldo()!=1){
                            jugador[j].setNombreJ(jugador[j+1].getNombreJ());
                            jugador[j].setPosicion(jugador[j+1].getPosicion());                            
                            jugador[j].setSueldo(jugador[j+1].getSueldo());                            
                            jugador[j].setValorMer(jugador[j+1].getValorMer());
                            LblNotificacion.setText("Dato eliminado");
                            i=20;
                        }
                    }
                }
            }
        }else if(TxtValorM.getText().equals("")==false){
           for(int i=0;i<20;i++){
                if(Integer.parseInt(TxtValorM.getText())==jugador[i].getValorMer()){
                     for(int j=i;j<20;j++){
                        if(jugador[j].getSueldo()!=1){
                            jugador[j].setNombreJ(jugador[j+1].getNombreJ());
                            jugador[j].setPosicion(jugador[j+1].getPosicion());                            
                            jugador[j].setSueldo(jugador[j+1].getSueldo());                            
                            jugador[j].setValorMer(jugador[j+1].getValorMer());
                            LblNotificacion.setText("Dato eliminado");
                            i=20;
                        }
                    }
                
            }
                
        }
           //Compara que la notificacion sea de dato eliminado y devuelve error al eliminar
           //get para obtener la cadena en el elemento en cuestion
           //Equals compara cadenas y devuelve true or false
        }if(LblNotificacion.getText().equals("Dato eliminado")==false){
                LblNotificacion.setText("Error al eliminar");
           }
        
        
    }//GEN-LAST:event_BtnEliminarActionPerformed
  
    
    private void BtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarActionPerformed
        // TODO add your handling code here:
        if(TxtNombreJ.getText().equals("")==false){
            for(int i=0;i<20;i++){
                if(TxtNombreJ.getText().equals(jugador[i].getNombreJ())){
                     TxtNombreJ.setText(jugador[i].getNombreJ());
                     TxtPosicion.setText(jugador[i].getPosicion());                            
                     TxtSueldo.setText(String.valueOf(jugador[i].getSueldo()));                            
                     TxtValorM.setText(String.valueOf(jugador[i].getValorMer()));
                     LblNotificacion.setText("Dato Consultado");
                       i=20;
                        } 
                    }
                
        }else if(TxtPosicion.getText().equals("")==false){
             for(int i=0;i<20;i++){
                if(TxtPosicion.getText().equals(jugador[i].getPosicion())){
                    TxtNombreJ.setText(jugador[i].getNombreJ());
                     TxtPosicion.setText(jugador[i].getPosicion());                            
                     TxtSueldo.setText(String.valueOf(jugador[i].getSueldo()));                            
                     TxtValorM.setText(String.valueOf(jugador[i].getValorMer()));
                     LblNotificacion.setText("Dato Consultado");
                       i=20;
                        }
                    }
             
        }else if(TxtSueldo.getText().equals("")==false){
            for(int i=0;i<20;i++){
                if(Integer.parseInt(TxtSueldo.getText())==jugador[i].getSueldo()){
                     TxtNombreJ.setText(jugador[i].getNombreJ());
                     TxtPosicion.setText(jugador[i].getPosicion());                            
                     TxtSueldo.setText(String.valueOf(jugador[i].getSueldo()));                            
                     TxtValorM.setText(String.valueOf(jugador[i].getValorMer()));
                     LblNotificacion.setText("Dato Consultado");
                       i=20;
                        }
                    }
            
        }else if(TxtValorM.getText().equals("")==false){
           for(int i=0;i<20;i++){
                if(Integer.parseInt(TxtValorM.getText())==jugador[i].getValorMer()){
                     TxtNombreJ.setText(jugador[i].getNombreJ());
                     TxtPosicion.setText(jugador[i].getPosicion());                            
                     TxtSueldo.setText(String.valueOf(jugador[i].getSueldo()));                            
                     TxtValorM.setText(String.valueOf(jugador[i].getValorMer()));
                     LblNotificacion.setText("Dato Consultado");
                       i=20;
                        
                    }
                }
            
           //Compara que la notificacion sea de dato eliminado y devuelve error al eliminar
           //get para obtener la cadena en el elemento en cuestion
           //Equals compara cadenas y devuelve true or false
        }else {
                LblNotificacion.setText("Error al consultar");
           }
    }//GEN-LAST:event_BtnConsultarActionPerformed

    private void TxtPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPosicionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Deportes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsultar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnRegistar;
    private javax.swing.JLabel LblNotificacion;
    private javax.swing.JTextField TxtNombreJ;
    private javax.swing.JTextField TxtPosicion;
    private javax.swing.JTextField TxtSueldo;
    private javax.swing.JTextField TxtValorM;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
